name: eShopOnWeb Build and Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  RESOURCE_GROUP: rg-eshoponweb
  LOCATION: westus2
  TEMPLATE_FILE: infra/webapp.bicep
  SUBSCRIPTION_ID: e86286fc-ea85-4b96-84ec-b677608fffc5
  WEBAPP_NAME: eshoponweb-webapp59060807

jobs:
  buildandtest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "8.0.x"
          dotnet-quality: "preview"

      - name: Build
        run: dotnet build ./eShopOnWeb.sln --configuration Release

      - name: Test
        run: dotnet test ./eShopOnWeb.sln --configuration Release

      - name: Publish
        run: |
          dotnet publish ./src/Web/Web.csproj -c Release -o ./publish
          cd ./publish
          zip -r ../app.zip .

      - name: Upload Web App Artifact
        uses: actions/upload-artifact@v5
        with:
          name: dotnet-app
          path: ./app.zip

      - name: Upload Bicep Template
        uses: actions/upload-artifact@v5
        with:
          name: bicep-template
          path: ./infra/webapp.bicep

  deploy:
    runs-on: ubuntu-latest
    needs: buildandtest
    environment:
      name: Development

    steps:
      - name: Download Web App Artifact
        uses: actions/download-artifact@v6
        with:
          name: dotnet-app
          path: ./

      - name: Download Bicep Template
        uses: actions/download-artifact@v6
        with:
          name: bicep-template
          path: ./infra

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Infrastructure
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          template: ./infra/webapp.bicep
          parameters: webAppName=${{ env.WEBAPP_NAME }} location=${{ env.LOCATION }}
          failOnStdErr: false

      - name: Deploy Web App
        uses: Azure/cli@v2
        with:
          inlineScript: |
            az webapp deploy \
              --name ${{ env.WEBAPP_NAME }} \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --src-path app.zip \
              --type zip
